import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';
import 'package:printing/printing.dart';
import 'dart:typed_data';

class ReportService {
  static Future<void> generateAndPrintMedicineReport(List<dynamic> medicines) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(level: 0, text: 'MediCheck AI - Medication Report'),
              pw.SizedBox(height: 20),
              pw.Text('Date: ${DateTime.now().toString()}'),
              pw.SizedBox(height: 20),
              pw.TableHelper.fromTextArray(
                context: context,
                data: <List<String>>[
                  <String>['Medicine Name', 'Uses', 'Side Effects'],
                  ...medicines.map((med) => [
                    med['name'] ?? 'N/A',
                    (med['uses'] is List ? (med['uses'] as List).join(', ') : med['uses']?.toString() ?? 'N/A'),
                    (med['sideEffects'] is List ? (med['sideEffects'] as List).join(', ') : med['sideEffects']?.toString() ?? 'N/A'),
                  ]),
                ],
              ),
              pw.Footer(
                margin: const pw.EdgeInsets.only(top: 20),
                trailing: pw.Text('Generated by MediCheck AI'),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'MediCheck_Report_${DateTime.now().millisecondsSinceEpoch}.pdf',
    );
  }
}
